service: gatsby-site

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

custom:
  siteName: gatsby-site-v3s2vl90bj

s3Sync:
  - bucketName: ${self:custom.siteName}
    localDir: public

# TODO: https://github.com/ServerlessOpsIO/serverless-zombo.com/blob/master/serverless.yml
resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]